import { Section, SystemType } from './types';
import { SectionOut } from '../../api/projects';

export function apiToLocal(s: SectionOut): Section {
  // Backwards compat: migrate legacy 'ДВЕРЬ' value
  const rawSystem = s.system === 'ДВЕРЬ' ? 'КОМПЛЕКТАЦИЯ' : s.system;
  return {
    id: String(s.id),
    name: s.name,
    system: (rawSystem as SystemType) || 'СЛАЙД',
    width: s.width,
    height: s.height,
    panels: s.panels,
    quantity: s.quantity,
    glassType: s.glass_type,
    paintingType: s.painting_type as Section['paintingType'],
    ralColor: s.ral_color,
    cornerLeft: s.corner_left,
    cornerRight: s.corner_right,
    externalWidth: s.external_width,
    rails: s.rails as 3 | 5 | undefined,
    threshold: s.threshold,
    firstPanelInside: s.first_panel_inside,
    unusedTrack: s.unused_track,
    interGlassProfile: s.inter_glass_profile,
    profileLeft: s.profile_left,
    profileRight: s.profile_right,
    lock: s.lock,
    handle: s.handle,
    floorLatchesLeft: s.floor_latches_left,
    floorLatchesRight: s.floor_latches_right,
    handleOffset: s.handle_offset,
    handleOffsetLeft: s.handle_offset_left,
    handleOffsetRight: s.handle_offset_right,
    profileLeftWall: s.profile_left_wall ?? false,
    profileLeftLockBar: s.profile_left_lock_bar ?? false,
    profileLeftPBar: s.profile_left_p_bar ?? false,
    profileLeftHandleBar: s.profile_left_handle_bar ?? false,
    profileLeftBubble: s.profile_left_bubble ?? false,
    profileRightWall: s.profile_right_wall ?? false,
    profileRightLockBar: s.profile_right_lock_bar ?? false,
    profileRightPBar: s.profile_right_p_bar ?? false,
    profileRightHandleBar: s.profile_right_handle_bar ?? false,
    profileRightBubble: s.profile_right_bubble ?? false,
    lockLeft: s.lock_left,
    lockRight: s.lock_right,
    bookSubtype: s.book_subtype,
    handleLeft: s.handle_left,
    handleRight: s.handle_right,
    doors: s.doors,
    doorSide: s.door_side,
    doorType: s.door_type,
    doorOpening: s.door_opening,
    compensator: s.compensator,
    angleLeft: s.angle_left,
    angleRight: s.angle_right,
    bookSystem: s.book_system,
    doorSystem: s.door_system,
    csShape: s.cs_shape,
    csWidth2: s.cs_width2,
    extraParts: s.extra_parts,
    comments: s.comments,
    documentOverrides: s.document_overrides,
  };
}

export function localToApi(s: Section, order: number): Omit<SectionOut, 'id' | 'project_id'> {
  return {
    name: s.name, order,
    system: s.system,
    width: s.width, height: s.height, panels: s.panels, quantity: s.quantity,
    glass_type: s.glassType, painting_type: s.paintingType,
    ral_color: s.ralColor, corner_left: s.cornerLeft, corner_right: s.cornerRight,
    external_width: s.externalWidth,
    rails: s.rails, threshold: s.threshold, first_panel_inside: s.firstPanelInside,
    unused_track: s.unusedTrack, inter_glass_profile: s.interGlassProfile,
    profile_left: s.profileLeft, profile_right: s.profileRight,
    lock: s.lock, handle: s.handle,
    floor_latches_left: s.floorLatchesLeft, floor_latches_right: s.floorLatchesRight,
    handle_offset: s.handleOffset,
    handle_offset_left: s.handleOffsetLeft,
    handle_offset_right: s.handleOffsetRight,
    profile_left_wall: s.profileLeftWall,
    profile_left_lock_bar: s.profileLeftLockBar,
    profile_left_p_bar: s.profileLeftPBar,
    profile_left_handle_bar: s.profileLeftHandleBar,
    profile_left_bubble: s.profileLeftBubble,
    profile_right_wall: s.profileRightWall,
    profile_right_lock_bar: s.profileRightLockBar,
    profile_right_p_bar: s.profileRightPBar,
    profile_right_handle_bar: s.profileRightHandleBar,
    profile_right_bubble: s.profileRightBubble,
    lock_left: s.lockLeft,
    lock_right: s.lockRight,
    book_subtype: s.bookSubtype,
    handle_left: s.handleLeft,
    handle_right: s.handleRight,
    doors: s.doors, door_side: s.doorSide, door_type: s.doorType,
    door_opening: s.doorOpening, compensator: s.compensator,
    angle_left: s.angleLeft, angle_right: s.angleRight, book_system: s.bookSystem,
    door_system: s.doorSystem, cs_shape: s.csShape, cs_width2: s.csWidth2,
    extra_parts: s.extraParts, comments: s.comments,
    document_overrides: s.documentOverrides,
  };
}
