from __future__ import annotations

from dataclasses import dataclass


DEFAULT_COLOR_VARIANTS = ("Анод", "RAL стандарт", "RAL нестандарт")


@dataclass(frozen=True)
class ProfileCatalogItem:
    article: str
    name: str
    image: str
    section_width_mm: float
    section_height_mm: float
    paint_mode: str
    color_variants: tuple[str, ...] = DEFAULT_COLOR_VARIANTS
    paint_note: str = ""
    group: str = "Профили"
    system: str = "СЛАЙД"
    unit: str = "м.п."
    purchase_price: float = 0
    markup_percent: float = 35
    weight: float = 0
    waste_percent: float = 4
    supplier: str = "Raluma"
    is_active: bool = True
    note: str = ""


PROFILE_CATALOG: dict[str, ProfileCatalogItem] = {
    "RS1313": ProfileCatalogItem(
        "RS1313",
        "Верхний направляющий профиль 3-рельсовый",
        "RS1313.png",
        72,
        53,
        "Красится",
        system="СЛАЙД 3",
        purchase_price=420,
        weight=0.72,
        note="Длина считается формулой, сечение используется для схем и документов",
    ),
    "RS1315": ProfileCatalogItem(
        "RS1315",
        "Верхний направляющий профиль 5-рельсовый",
        "RS1315.png",
        119,
        53,
        "Красится",
        system="СЛАЙД 5",
        purchase_price=580,
        weight=0.96,
        note="Пять рельсов, геометрия нужна для масштабной схемы",
    ),
    "RS2323": ProfileCatalogItem(
        "RS2323",
        "Порог 3-рельсовый",
        "RS2323.png",
        76,
        23,
        "Частично",
        paint_note="НЕ КРАСИТЬ!!!",
        system="СЛАЙД 3",
        purchase_price=380,
        weight=0.61,
        note="В заявке на покраску отмечать область, которую не красить",
    ),
    "RS2325": ProfileCatalogItem(
        "RS2325",
        "Порог 5-рельсовый",
        "RS2325.png",
        122,
        23,
        "Частично",
        paint_note="НЕ КРАСИТЬ!!!",
        system="СЛАЙД 5",
        purchase_price=520,
        weight=0.88,
        note="В заявке на покраску отмечать область, которую не красить",
    ),
    "RS23231": ProfileCatalogItem(
        "RS23231",
        "Порог накладной 3-рельсовый",
        "RS23231.png",
        76,
        11,
        "Частично",
        paint_note="НЕ КРАСИТЬ!!!",
        system="СЛАЙД 3",
        purchase_price=340,
        weight=0.32,
        note="Накладной порог, верхние бобышки не красить",
    ),
    "RS23251": ProfileCatalogItem(
        "RS23251",
        "Порог накладной 5-рельсовый",
        "RS23251.png",
        122,
        11,
        "Частично",
        paint_note="НЕ КРАСИТЬ!!!",
        system="СЛАЙД 5",
        purchase_price=460,
        weight=0.46,
        note="Накладной порог, верхние бобышки не красить",
    ),
    "RS2333": ProfileCatalogItem(
        "RS2333",
        "Пристеночный профиль 3-рельсовый",
        "RS2333.png",
        76,
        16,
        "Красится",
        system="СЛАЙД 3",
        purchase_price=330,
        weight=0.42,
        note="На схеме сверху добавляет 16 мм с выбранной стороны",
    ),
    "RS2335": ProfileCatalogItem(
        "RS2335",
        "Пристеночный профиль 5-рельсовый",
        "RS2335.png",
        122,
        16,
        "Красится",
        system="СЛАЙД 5",
        purchase_price=450,
        weight=0.58,
        note="На схеме сверху добавляет 16 мм с выбранной стороны",
    ),
    "RS2081": ProfileCatalogItem(
        "RS2081",
        "Боковой П-образный профиль-замок",
        "RS2081.png",
        57,
        25,
        "Красится",
        paint_note="КРАСИТЬ ВЕСЬ ПЕРИМЕТР",
        purchase_price=510,
        markup_percent=38,
        weight=0.82,
        note="Используется при боковом замыкании, красить весь периметр",
    ),
    "RS1082": ProfileCatalogItem(
        "RS1082",
        "Боковой П-профиль",
        "RS1082.png",
        25,
        25,
        "Красится",
        purchase_price=260,
        weight=0.36,
        note="Боковой профиль без замка",
    ),
    "RS112": ProfileCatalogItem(
        "RS112",
        "Профиль-ручка",
        "RS112.png",
        52,
        40,
        "Красится",
        purchase_price=420,
        weight=0.74,
        note="Основная ручка для стандартного СЛАЙД",
    ),
    "RS2061": ProfileCatalogItem(
        "RS2061",
        "Межстекольный профиль",
        "RS2061.png",
        20,
        12,
        "Красится",
        purchase_price=210,
        weight=0.28,
        note="В схеме сверху зеркалится по направлению первой панели",
    ),
    "RS1006": ProfileCatalogItem(
        "RS1006",
        "Прозрачный межстекольный",
        "RS1006.png",
        20,
        12,
        "Не красится",
        ("Без цвета",),
        purchase_price=0,
        weight=0,
        note="Прозрачный межстекольный профиль, перехлест между стеклами 9,5 мм",
    ),
    "RS3061": ProfileCatalogItem(
        "RS3061",
        "Профиль с зацепом",
        "RS3061.png",
        18.8,
        18.8,
        "Не красится",
        ("Без цвета",),
        purchase_price=0,
        weight=0,
        note="Заменяет старый h-профиль RS1004, перехлест между стеклами 11,5 мм",
    ),
    "RS2021": ProfileCatalogItem(
        "RS2021",
        "Стекольный профиль",
        "RS2021.png",
        75,
        18,
        "Красится",
        purchase_price=190,
        weight=0.24,
        note="Длина считается отдельно по каждому стеклу",
    ),
    "RS1002": ProfileCatalogItem(
        "RS1002",
        "Пузырьковый уплотнитель",
        "RS1002.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Уплотнители",
        purchase_price=86,
        markup_percent=45,
        weight=0.09,
        waste_percent=8,
        supplier="Склад",
        note="Норма зависит от стороны установки",
    ),
    "RS205": ProfileCatalogItem(
        "RS205",
        "Защёлка в пол",
        "RS205.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Защёлки",
        unit="шт",
        purchase_price=185,
        markup_percent=40,
        weight=0.12,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Ставится слева/справа по настройкам секции",
    ),
    "RS1083": ProfileCatalogItem(
        "RS1083",
        "Соединительный профиль 30×20×30",
        "RS1083.png",
        30,
        20,
        "Красится",
        purchase_price=0,
        weight=0,
        note="Для центральных ручек-профилей RS112 в системе СЛАЙД 2 ряда",
    ),
    "RS108": ProfileCatalogItem(
        "RS108",
        "Заглушка стекольного центральная",
        "RS108.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Фурнитура",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Центральные створки СЛАЙД 2 ряда",
    ),
    "RU010": ProfileCatalogItem(
        "RU010",
        "Магнитный уплотнитель",
        "",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Уплотнители",
        unit="м.п.",
        purchase_price=0,
        markup_percent=35,
        weight=0,
        waste_percent=4,
        supplier="Склад",
        note="Используется с центральными ручками-профилями RS112",
    ),
    "RS3110": ProfileCatalogItem(
        "RS3110",
        "h-уплотнитель центрального стыка",
        "RS3110.jpg",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Профили",
        unit="м.п.",
        purchase_price=0,
        markup_percent=35,
        weight=0,
        waste_percent=4,
        supplier="Склад",
        note="Для центрального стыка СЛАЙД 2 ряда, кроме варианта с центральными RS112",
    ),
    "RS123": ProfileCatalogItem(
        "RS123",
        "Ответная планка замка RS3020",
        "RS123.jpg",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Фурнитура",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Ставится по одной планке на каждый замок RS3020",
    ),
    "RU003": ProfileCatalogItem(
        "RU003",
        "Ролик 2-колесный",
        "RU003.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Фурнитура",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Для панелей шириной до 500 мм",
    ),
    "RU005": ProfileCatalogItem(
        "RU005",
        "Ролик 4-колесный",
        "RU005.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Фурнитура",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Для панелей шириной больше 500 мм",
    ),
    "RS206": ProfileCatalogItem(
        "RS206",
        "Накидная защёлка на 2 створки",
        "RS206.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Защёлки",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Центральная накидная защёлка для СЛАЙД 2 ряда",
    ),
    "RS30301": ProfileCatalogItem(
        "RS30301",
        "Замок стекло-стекло",
        "RS30301.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Замки",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Временный артикул замка стекло-стекло для центральных панелей",
    ),
    "RS3014": ProfileCatalogItem(
        "RS3014",
        "Ручка-кноб",
        "RS3014.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Ручки",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Боковые и центральные панели СЛАЙД",
    ),
    "RS3017": ProfileCatalogItem(
        "RS3017",
        "Стеклянная ручка",
        "RS3017.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Ручки",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Боковые и центральные панели СЛАЙД",
    ),
    "RS30201": ProfileCatalogItem(
        "RS30201",
        "Ручка-скоба 600мм",
        "RS30201.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Ручки",
        unit="шт",
        purchase_price=0,
        markup_percent=40,
        weight=0,
        waste_percent=0,
        supplier="Фурнитура СПБ",
        note="Боковые и центральные панели СЛАЙД",
    ),
    "DIN7504M": ProfileCatalogItem(
        "DIN7504M",
        "Саморез сверлоконечный",
        "DIN7504M.png",
        0,
        0,
        "Не красится",
        ("Без цвета",),
        group="Крепёж",
        system="Все",
        unit="шт",
        purchase_price=3.8,
        markup_percent=60,
        weight=0.004,
        waste_percent=3,
        supplier="Метизы",
        note="Формула количества будет уточняться отдельно",
    ),
}


def get_profile_catalog_item(article: str | None) -> ProfileCatalogItem | None:
    if not article:
        return None
    return PROFILE_CATALOG.get(article)


def apply_profile_catalog(profile) -> None:
    item = get_profile_catalog_item(getattr(profile, "article", ""))
    if not item:
        return
    profile.image = item.image
    profile.section_width_mm = item.section_width_mm
    profile.section_height_mm = item.section_height_mm
    profile.paint_mode = item.paint_mode
    profile.color_variants = list(item.color_variants)
    profile.paint_note = item.paint_note
